# Generated by Django 2.2 on 2020-11-20 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
