# Generated by Django 2.2 on 2020-11-19 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='quanity',
            new_name='quantity',
        ),
    ]
