# Generated by Django 2.2 on 2020-11-24 05:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(blank=True, choices=[('ADDNEW', 'Add New Item'), ('ADDSTOCK', 'Add Stock'), ('REMOVE', 'Remove')], max_length=50),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='updated_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transaction_item', to='ThereItIs_app.Item'),
        ),
    ]
