# Generated by Django 2.2 on 2020-11-20 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0002_item_mainimage'),
        ('ThereItIs_app', '0002_auto_20201119_0759'),
    ]

    operations = [
    ]
