# Generated by Django 2.2 on 2020-11-24 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0002_auto_20201123_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='item_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='transaction',
            name='item_sku',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
