# Generated by Django 2.2 on 2020-11-21 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ThereItIs_app', '0003_merge_20201120_0716'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='mainimage',
            field=models.ImageField(blank=True, upload_to='ThereItIs_app/static/media/'),
        ),
    ]
